[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pls_verify = "Hd3SURXCp7fnnqWRYLPRQbLy5qm8kL8V8ukSLWy2Viw8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pavlo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
